server:
  port: 9201
spring:
  application:
    name: oauth2-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes: # 配置路由规则
        - id: oauth-api-route
          uri: lb://oauth2-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: auth-server-route
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能
          lower-case-service-id: true  #使用小写服务名，默认是大写
    sentinel:
      transport:
        dashboard: localhost:8090
        port: 8719
      # 服务启动直接建立心跳连接
      eager: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9401/rsa/publicKey
          #配置RSA的公钥访问地址
#网关白名单配置
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
logging:
  level:
    org.springframework.security: DEBUG
