server:
  port: 9503
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.alibaba.nacos: DEBUG